# Generated by Django 3.2 on 2022-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_model', '0002_auto_20220509_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='rating',
            field=models.IntegerField(default='00'),
        ),
    ]
